include_recipe 'deploy'

Chef::Log.info("Entering docker-compose-deploy")

node[:deploy].each do |application, deploy|

  if node[:opsworks][:instance][:layers].first != deploy[:environment_variables][:layer]
    Chef::Log.warn("Skipping deploy::docker-compose application #{application} as it is not deployed to this layer")
    next
  end

  opsworks_deploy_dir do
    user deploy[:user]
    group deploy[:group]
    path deploy[:deploy_to]
  end

  opsworks_deploy do
    deploy_data deploy
    app application
  end

  bash "reset env file" do
    user "root"
    code <<-EOH
      rm -f #{deploy[:deploy_to]}/.env
      touch #{deploy[:deploy_to]}/.env
    EOH
  end

  open(deploy[:deploy_to] + '/.env', 'a') do |f|
    f.puts "# this file is autogenerated"
    deploy[:environment_variables].each do |name, value|
      f.puts "#{name}=#{value}"
    end
  end

  Chef::Log.info('Docker compose pull start')
  bash "docker-compose pull" do
    user "root"
    code <<-EOH
      docker-compose -f docker-compose.prod.yml pull
    EOH
  end

  Chef::Log.info('docker-compose-run start')
  bash "docker-run" do
    user "root"
    code <<-EOH
      docker-compose down
      docker-compose -f docker-compose.prod.yml up -d
    EOH
  end

end
Chef::Log.info("Exiting docker-compose-deploy")
